name: Restart

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
    - name: HTTP Request Action
      id: botRestart
      uses: fjogeleit/http-request-action@v1.8.2
      with:
        url: ${{ secrets.DEPLOY_URL }}
        method: 'POST'
        data: '{"signal": "restart"}'
        bearerToken: ${{ secrets.DEPLOY_KEY }}
    - name: Show Response
      run: echo ${{ steps.botRestart.outputs.response }}
    - run: echo DONE!
